---
## Install Oh-my-zsh
- name: Install zsh 
  apt: name=zsh state=latest

- name: Check if already exists {{ user_home_path }}/.oh-my-zsh folder
  stat: path={{ user_home_path }}/.oh-my-zsh
  register: ohmyzsh_stat

- name: Clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest={{ user_home_path }}/.oh-my-zsh accept_hostkey=yes
  when: ohmyzsh_stat.stat.exists == False

- name: Clone oh-my-zsh repo
  git: repo=https://github.com/bhilburn/powerlevel9k.git dest={{ user_home_path }}/.oh-my-zsh/custom/themes/powerlevel9k accept_hostkey=yes
  when: ohmyzsh_stat.stat.exists == False

- name: Check if already exists conf folder
  stat: path={{ user_home_path }}/.oh-my-zsh
  register: ohmyzsh_config_stat

- name: Create conf folder in home directory
  file: path={{ user_home_path }}/conf/ state=directory owner={{ user }} group={{ group_name }}
  when: ohmyzsh_config_stat.stat.exists == False

- name: deploy .zshrc
  template: src=zshrc.j2 dest={{ user_home_path }}/conf/zshrc owner={{ user }} group={{ group_name }}
  
- name: remove standard zshrc
  file: path={{ user_home_path }}/.zshrc state=absent

- name: symlink zshrc
  file: path={{ user_home_path }}/.zshrc src={{ user_home_path }}/conf/zshrc state=link owner={{ user }} group={{ group_name }}

- name: Set zsh as default shell
  user: name={{ user }} shell=/bin/zsh
  when: ohmyzsh_stat.stat.exists == False